// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: protofiles/Formatting.proto

package formatting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FormattingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ConvertedString string `protobuf:"bytes,1,opt,name=convertedString,proto3" json:"convertedString,omitempty"`
}

func (x *FormattingResponse) Reset() {
	*x = FormattingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_Formatting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormattingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormattingResponse) ProtoMessage() {}

func (x *FormattingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_Formatting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormattingResponse.ProtoReflect.Descriptor instead.
func (*FormattingResponse) Descriptor() ([]byte, []int) {
	return file_protofiles_Formatting_proto_rawDescGZIP(), []int{0}
}

func (x *FormattingResponse) GetConvertedString() string {
	if x != nil {
		return x.ConvertedString
	}
	return ""
}

type FormattingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StringToConvert string `protobuf:"bytes,1,opt,name=stringToConvert,proto3" json:"stringToConvert,omitempty"`
}

func (x *FormattingRequest) Reset() {
	*x = FormattingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protofiles_Formatting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FormattingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FormattingRequest) ProtoMessage() {}

func (x *FormattingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protofiles_Formatting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FormattingRequest.ProtoReflect.Descriptor instead.
func (*FormattingRequest) Descriptor() ([]byte, []int) {
	return file_protofiles_Formatting_proto_rawDescGZIP(), []int{1}
}

func (x *FormattingRequest) GetStringToConvert() string {
	if x != nil {
		return x.StringToConvert
	}
	return ""
}

var File_protofiles_Formatting_proto protoreflect.FileDescriptor

var file_protofiles_Formatting_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x2f, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x22, 0x3e, 0x0a, 0x12, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x0f,
	0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x64, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x65, 0x64,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x22, 0x3d, 0x0a, 0x11, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x0f, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x43, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x6f, 0x43, 0x6f,
	0x6e, 0x76, 0x65, 0x72, 0x74, 0x32, 0xeb, 0x01, 0x0a, 0x11, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x54,
	0x6f, 0x43, 0x61, 0x6d, 0x65, 0x6c, 0x43, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73,
	0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x54, 0x6f, 0x4c, 0x6f, 0x77, 0x65, 0x72, 0x43, 0x61,
	0x73, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x46, 0x6f, 0x72,
	0x6d, 0x61, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b,
	0x2e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x0b, 0x54,
	0x6f, 0x55, 0x70, 0x70, 0x65, 0x72, 0x43, 0x61, 0x73, 0x65, 0x12, 0x1a, 0x2e, 0x73, 0x74, 0x72,
	0x69, 0x6e, 0x67, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x73,
	0x2e, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x74,
	0x69, 0x6e, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protofiles_Formatting_proto_rawDescOnce sync.Once
	file_protofiles_Formatting_proto_rawDescData = file_protofiles_Formatting_proto_rawDesc
)

func file_protofiles_Formatting_proto_rawDescGZIP() []byte {
	file_protofiles_Formatting_proto_rawDescOnce.Do(func() {
		file_protofiles_Formatting_proto_rawDescData = protoimpl.X.CompressGZIP(file_protofiles_Formatting_proto_rawDescData)
	})
	return file_protofiles_Formatting_proto_rawDescData
}

var file_protofiles_Formatting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protofiles_Formatting_proto_goTypes = []interface{}{
	(*FormattingResponse)(nil), // 0: strings.FormattingResponse
	(*FormattingRequest)(nil),  // 1: strings.FormattingRequest
}
var file_protofiles_Formatting_proto_depIdxs = []int32{
	1, // 0: strings.FormattingService.ToCamelCase:input_type -> strings.FormattingRequest
	1, // 1: strings.FormattingService.ToLowerCase:input_type -> strings.FormattingRequest
	1, // 2: strings.FormattingService.ToUpperCase:input_type -> strings.FormattingRequest
	0, // 3: strings.FormattingService.ToCamelCase:output_type -> strings.FormattingResponse
	0, // 4: strings.FormattingService.ToLowerCase:output_type -> strings.FormattingResponse
	0, // 5: strings.FormattingService.ToUpperCase:output_type -> strings.FormattingResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protofiles_Formatting_proto_init() }
func file_protofiles_Formatting_proto_init() {
	if File_protofiles_Formatting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protofiles_Formatting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormattingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protofiles_Formatting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FormattingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protofiles_Formatting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protofiles_Formatting_proto_goTypes,
		DependencyIndexes: file_protofiles_Formatting_proto_depIdxs,
		MessageInfos:      file_protofiles_Formatting_proto_msgTypes,
	}.Build()
	File_protofiles_Formatting_proto = out.File
	file_protofiles_Formatting_proto_rawDesc = nil
	file_protofiles_Formatting_proto_goTypes = nil
	file_protofiles_Formatting_proto_depIdxs = nil
}
